-- 创建源数据表
DROP TABLE IF EXISTS `BI_DATASOURCE`;
CREATE TABLE IF NOT EXISTS `BI_DATASOURCE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增长主键',
  `SOURCE_CODE` varchar(200) NOT NULL DEFAULT '' COMMENT '数据源编码',
  `SOURCE_URL` varchar(500) NOT NULL DEFAULT '' COMMENT '数据源连接地址',
  `SOURCE_USER` varchar(50) DEFAULT NULL COMMENT '数据源用户',
  `SOURCE_PASSWORD` varchar(200) DEFAULT NULL COMMENT '数据源密码',
  `SOURCE_TYPE` varchar(50) NOT NULL DEFAULT 'MYSQL' COMMENT '数据源类型',
  `CREATE_TIME` datetime NOT NULL COMMENT '创建时间',
  `LAST_UPDATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UNQ_SOURCE_CODE` (`SOURCE_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- 创建Hadoop输出表信息
DROP TABLE IF EXISTS `BI_HADOOP_OUTPUT`;
CREATE TABLE IF NOT EXISTS `BI_HADOOP_OUTPUT` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增长主键',
  `OBJECT_TYPE` varchar(50) NOT NULL DEFAULT 'FILE' COMMENT '对象类型：HADOOP',
  `DATA_PATH` varchar(1000) NOT NULL DEFAULT '' COMMENT '数据输出路径',
  `CREATE_HIVE_TABLE` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否创建Hive表',
  `HIVE_EXTERNAL_TABLE` varchar(500) DEFAULT NULL COMMENT 'Hive外表的路径',
  `HIVE_SCHEMA` varchar(50) DEFAULT NULL COMMENT 'Hive的Schema名称',
  `OUTPUT_ENV` varchar(500) DEFAULT NULL COMMENT '数据输出的环境',
  `CREATE_TIME` datetime NOT NULL COMMENT '创建时间',
  `LAST_UPDATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- 创建ETL Job的定义表
DROP TABLE IF EXISTS `BI_ETL_JOB_DEFINE`;
CREATE TABLE IF NOT EXISTS `BI_ETL_JOB_DEFINE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增长主键',
  `DEFINE_NAME` varchar(200) NOT NULL DEFAULT '' COMMENT '定义名称',
  `INPUT_SOURCE_ID` bigint(20) NOT NULL COMMENT '输入数据源ID',
  `OUTPUT_SOURCE_ID` bigint(20) NOT NULL COMMENT '输出数据源ID',
  `TASK_NUM` int(11) NOT NULL DEFAULT '10' COMMENT '任务数量',
  `TABLE_MAPPERS` varchar(2000) NOT NULL DEFAULT '[]' COMMENT '表映射关系描述',
  `OUTPUT_TYPE` varchar(200) NOT NULL DEFAULT 'HADOOP' COMMENT '输出类型',
  `CREATE_TIME` datetime NOT NULL COMMENT '创建时间',
  `LAST_UPDATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UNQ_DEF_NAME` (`DEFINE_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;